# Generated by Django 2.0.2 on 2018-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('tweet', models.CharField(max_length=280)),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
